### ISSUE TITLE
plots#create "undefined method `name' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1198]
A NoMethodError occurred in plots#create:

  undefined method `name' for nil:NilClass
  config/initializers/apartment.rb:52:in`call'

Parameters : {"format"=>"xml", "controller"=>"keyfield/v1/plots", "action"=>"create"}

**Comment by tudro** [comment]
Hello,

My name is Tudor and I'm working on the keyfield dev team. Can you please tell me if this bug is caused by some bad data that we send? 

Thank you

**Comment by igkyab** [comment]
Hello Tudor, nice to meet you. My name is Alexander and i'm working on the Ekylibre dev team.

I think the problem is throw because you specify a bad CultivableZone UUID. We have the following code in our plugin :

```
          cultivable_zone = CultivableZone.find_or_initialize_by(uuid: plot.attr('uuid'))
          cultivable_zone.name = plot.attr('name')
```

Parameters of the request : {"format"=>"xml", "controller"=>"keyfield/v1/plots", "action"=>"create"}

We have very few details for this bug.

**Comment by tudro** [comment]
Hello Alexander,

Hmmm, strange. I create the UUID with a function directly from the java sdk. So it should generate the proper thing every time.

Maybe it was from some tests from our dev/preprod where we might have bugs, DB can be corrupt, etc. If you get this again please let me know. If possible, please give me a date/time when this happens so that i can know where to look in the logs.

**Comment by burisu** [comment]
I closed for now.
