### ISSUE TITLE
parcels#give (NoMethodError) "undefined method `id' for nil:NilClass"

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1264]
A NoMethodError occurred in parcels#give:

  undefined method `id' for nil:NilClass
  app/models/journal_entry.rb:360:in `add!'

**Comment by Aquaj** [comment]
**Source:** Variant in the parcel has no stock_movement_account, even though its ProductNatureCategory has one.
No development can fix the problem itself as it is due to the natural evolution of the platform functionalities'. It should pop up less and less though as Variants are going to be more and more ones created with more recent code (and thus without that lack of stock_*_accounts).

**Solution:** Make the user modify-save (no actual modification needed) their variant so that it will automatically update its account based on its Category, the problem should then be fixed.
