### ISSUE TITLE
Remove 7% default VAT used for parcel 

### ISSUE THREAD

**Issue by AnneKappy** [ekylibre/ekylibre#1467]
When you generate a parcel, default VAT settings are on 7% : it doesn't exist any more and you can't select it in the list. Then you arrive on the purchase page where VAT is 0% whereas tax inclued amount is different from without tax amount.
![image](https://cloud.githubusercontent.com/assets/23054955/21093624/2057a03c-c053-11e6-96d9-fee797c64abb.png)

**Comment by chetannibotechnologies** [comment]
The Issue does not exist. It is working correctly in demo site and local machine.

**Comment by PH64** [comment]
@chetannibotechnologies, sorry but this issue already exist.
1- in the catalog price, you see a product with VAT preference (ex: "acide lactique - 25kg" with "TVA Française normale 2014" on https://demo.ekylibre.farm/backend/catalogs/1)
2- you make a parcel with "acide lactique - 25kg"
3- you invoice this parcel
4- in your sale, the VAT isn't right. You must have "20% TVA Française normale" and not a other VAT

**Comment by burisu** [comment]
Thanks @PH64 for explanations

**Comment by chetannibotechnologies** [comment]
When I have selected **acide lactique - 25kg** from variant drop-down then tax has been taking **20% TVA Française normale** by default. Tax **7% (fr) TVA import/export** showing because you can select tax directly from the drop-down without selecting variant. If we will disable the **Tax** drop-down then can this solve our problem?

**Comment by PH64** [comment]
@chetannibotechnologies,
There is no problem when you write an invoice directly.
The problem is when you transfer a parcel in invoice : the price of the variant is OK, tax is wrong compared to the taxe in the catalog price. 
The tax use, must be the tax used in the catalog price and this tax must be able to be change in the invoice
