### ISSUE TITLE
issues#create (ActiveRecord::StatementInvalid) "PG::InternalError: ERREUR: parse error - invalid geometry\n...

### ISSUE THREAD

**Issue by igkyab** [ekylibre/ekylibre#1698]
## Error
An ActiveRecord::StatementInvalid occurred in issues#create:

  PG::InternalError: ERREUR:  parse error - invalid geometry
ASTUCE : "Ba" <-- parse error at position 2 within geometry
: SELECT ST_AsEWKT(ST_GeomFromEWKT('Bat'))
  lib/charta.rb:85:in `select_value'

---
## Environment
- **Version :** 2.35.0
- **Date :** 24/02/2017
- **Server :** production

**Comment by TylerRick** [comment]
Hi, I'm running into the same error with a simple Rails/PostGIS app (not ekylibre). Could you please tell me what you did to fix this error?

I searched the commits in your project didn't see where/how you fixed the error, nor does it say in this issue why you closed the issue on August 3. Did you ever find a solution?

It looks like you may have stopped using PostGIS queries altogether in charta in this commit:
```
commit 9e7253acb5f7bc2c97ed065b66937ca3ecbb5466
Author: Brice TEXIER <brice@ekylibre.com>
Date:   2017-07-09 15:21:03 +0200

    Removes all dependencies to AR and adds RGeo::SVG

...
-        geom_ewkt = select_value("SELECT ST_AsEWKT(ST_GeomFromText('#{coordinates.as_text}', #{coordinates.srid}))")
+        geom_ewkt = "SRID=#{coordinates.srid};#{coordinates.as_text}"
...
```

I will probably open an issue in the activerecord-postgis-adapter or rgeo project as soon as I figure out which of those is to blame.

But just in case you know, I thought I would ask here first, since this is the top result that comes up when I search Google for this error message.

---

In my case, I'm trying to use a simple string `replace` function, and it incorrectly tries to parse my text string as WKT data.

I'm not sure what the `'Bat`` input to `ST_GeomFromEWKT` was in your case, but it looks like it was doing the same thing and incorrectly tries to parse a plain text string as if it was WKT data.

My code:
```
class Place < ActiveRecord::Base
  places = Place.arel_table
  scope :search_for, ->(query) {
    # This works:
    #name = places[:name]
    # But as soon as I try to use a function, it incorrectly tries to wrap the string in
    # ST_GeomFromEWKT:
    name = Arel::Nodes::NamedFunction.new('replace', [places[:name], 'Place', ''])
    where( name.matches("%#{query}%") )
  }
end
```

Reproducing the error in a console:
```
irb(main):010:0> Place.search_for('The Place')
  Place Load (1.0ms)  SELECT  "places".* FROM "places" WHERE (replace("places"."name", ST_GeomFromEWKT('Place'), ST_GeomFromEWKT('')) ILIKE '%The Place%') LIMIT $1  [["LIMIT", 11]]
ActiveRecord::StatementInvalid: PG::InternalError: ERROR:  parse error - invalid geometry
HINT:  "Pl" <-- parse error at position 2 within geometry
: SELECT  "places".* FROM "places" WHERE (replace("places"."name", ST_GeomFromEWKT('Place'), ST_GeomFromEWKT('')) ILIKE '%The Place%') LIMIT $1
```
Any ideas?

**Comment by TylerRick** [comment]
I think I figured it out: I just needed to wrap my string literals with `Arel::Nodes.build_quoted`.

So this works:
```
  places = self.arel_table
  scope :search_for, ->(query) {
    name = Arel::Nodes::NamedFunction.new('replace', [
        places[:name],
        Arel::Nodes.build_quoted('Place'),
        Arel::Nodes.build_quoted('')])
    where( name.matches("%#{query}%") )
  }
```

The error is actually more helpful when *not* using postgis adapter, because it hints at the solution:
```
Arel::Visitors::UnsupportedVisitError: Unsupported argument type: String. Construct an Arel node instead.
from gems/arel-8.0.0/lib/arel/visitors/to_sql.rb:735:in `unsupported'
```
The solution, of course, is to use an actual Arel node object instead of a plain string.
```
> value = Arel::Nodes.build_quoted('Value')
=> #<Arel::Nodes::Quoted:0x005617a5988c40 @expr="Value">
> value.is_a? Arel::Nodes::Node
=> true
```

Using string values directly *used* to work in the old version of arel/rgeo/etc. that I am upgrading from, which is why I assumed this was a bug. But it appears it was an intentional change in arel 6.0.0 (2014-11-25).

This was changed in rails/arel@93d72131bcc24ccb5536bec672d2dac94f8de651
```
Author: Aaron Patterson <aaron.patterson@gmail.com>
Date:   2014-03-24 16:26:09 -0700

    add the casting node to the AST at build time
    
    If we add the casting node to the ast at build time, then we can avoid
    doing the lookup at visit time.
```
```
-      alias :visit_String                        :quoted
+      alias :visit_String                        :unsupported
```
Seems like the arel documentation should mention needing to use `Arel::Nodes.build_quoted` whenever you have string literals that you pass to functions...
