### ISSUE TITLE
Time graphs of the workers is false

### ISSUE THREAD

**Issue by PH64** [ekylibre/ekylibre#1856]
The time graphs of the workers indicate the working times of the interventions and not the time spent by the workers

![capture du 2017-05-03 20-46-48](https://cloud.githubusercontent.com/assets/12525665/25676258/baf7a5d4-3041-11e7-9a33-3343baa2ced7.png)

### 1- How to reproduce?
Go to Settings > Workers and select a worker. The graph "time spent by activity" indicate the total duration of each intervention, but not the time spent by the worker on each of them.

### 2- What is really expected?
The graph should tell us the time spent only by the worker by activity based on their working period (see InterventionWorkingPeriod) if any given else if no working period related to worker in the intervention we will use current computation (global intervention time).

### 3- How to test it?
Go to Settings > Workers and select a worker. See if the time indicated by activity correspond to the time spent by the worker on this activity.

**Comment by linuxipho** [comment]
### 1- How to reproduce?
Go to Settings > Workers and select a worker. The graph "time spent by activity" indicate the total duration of each intervention, but not the time spent by the worker on each of them.
### 2- What is really expected?
The graph should tell us the time spent only by the worker by activity.
### 3- How to test it?
Go to Settings > Workers and select a worker. See if the time indicated by activity correspond to the time spent by the worker on this activity.

**Comment by sandy1987** [comment]
If I'm not getting it wrong, we have to change the graph where it will show total working period of time for each activity by the worker. Like as shown in below attached image

![time-graph](https://user-images.githubusercontent.com/4862281/27084616-2ce97076-506a-11e7-8ca7-5af16048a3bd.png)

Is it correct or I'm missing something ?

**Comment by Aquaj** [comment]
Unfortunately this was not what was meant.

The Workers are rattached to Interventions in two ways:
 - Through the `InterventionDoer` model.
 - Through the `InterventionParticipation` model.

The `InterventionParticipation` model is used when recording Interventions through the mobile app and as such has a more precise information on how much time (`InterventionWorkingPeriods`) a Worker has spent working, but it is not present for many interventions since most of them are recorded through the web app.

What we'd like is not a very different graph from the first one but rather one where the total duration for a worker uses that more precise value when available instead of the total intervention duration.

Example
```
Intervention Name | Workers  | Filled on mobile/webapp | Intervention duration | Worker participation duration
Intervention N°1  | Worker 1 | Filled on webapp        | 3h                    | Not present (filled by webapp)
Intervention N°2  | Worker 1 | Filled on mobile        | 2h                    | 1h30

Current graph will show (3h + 2h) = 5h
                        Î     Î----  Intervention time
                        --------- Intervention time
It should display (3h + 1h30) = 4h30
                     Î   Î----  Intervention participation time since it is available
                     --------- Intervention time
```

**Comment by sandy1987** [comment]
With the previous graph they are calculating working period only and if I'm not getting it wrong from your provided details, we have to consider actual work time out of total duration. Just in case if we don't have actual work time then will consider total duration.

Their is relation between these tables/models:
     Intervention, InterventionDoer, InterventionParticipation & InterventionWorkingPeriod

InterventionParticipation and InterventionDoer does not include any duration or start/stop time
While Intervention include working_duration as well as whole_duration with started_at and stopped_at time
and in the same way InterventionWorkingPeriod include duration with started_at and stopped_at time

I've compare whole_duration of intervention with duration of working periods of each intervention respectively and find slight difference in some cases.

If we are on the same track then I think we want a graph which will show intervention duration of each activity and in case if working period is present then will show working period duration for each activity instead of whole intervention duration.

  Ex: 
    With dummy data some details for one intervention is as shown below:-

    Intervention: 
      working_duration: 39360,
      whole_duration: 54060,

    Intervention working periods for the above intervention:
    { 1: {  started_at: Fri, 01 Jul 2016 11:16:00 IST +05:30,
            stopped_at: Fri, 01 Jul 2016 14:15:00 IST +05:30,
            duration: 10740 },
      2: {  started_at: Fri, 01 Jul 2016 18:20:00 IST +05:30,
            stopped_at: Sat, 02 Jul 2016 02:17:00 IST +05:30,
            duration: 28620, }      
    }

    intervention whole duration: 54060
    intervention working periods duration: 39360

    With new graph you want to show 39360 as working duration, are we on the same track ?

**Comment by Aquaj** [comment]
Not exactly.

It is not a matter of `Intervention.whole_duration` vs `Intervention.working_periods.sum(:duration)` but of which working periods to sum on.
InterventionParticipation and InterventionDoer do not contain a duration but through them you can access the working_periods to use
```
Worker --(:participations)--> InterventionParticipation --(:working_periods)--> InterventionWorkingPeriod.sum(:duration)
```
VS
```
Worker --(:interventions, through: :doers)--> Intervention.working_duration (which is always equal to Intervention.working_periods.sum(:duration))```

**Comment by sandy1987** [comment]
Hello, will you please elaborate this condition
```
Worker --(:interventions, through: :doers)--&gt; Intervention.working_duration (which is always equal to Intervention.working_periods.sum(:duration))
```
As with below condition, I understand that here we are calculating working period time for a worker for all 
of it's participations.
```
Worker --(:participations)--> InterventionParticipation --(:working_periods)--> InterventionWorkingPeriod.sum(:duration)
```

**Comment by Aquaj** [comment]
When a Worker's part in an intervention isn't represented by an InterventionParticipation, it is represented by an InterventionDoer.
So a Worker can access an Intervention though its InterventionDoer (`Worker --(:interventions, through: :doers) -> Intervention`).

The data model is : 
```
Worker ----------- InterventionDoer -------- Intervention ------- InterventionWorkingPeriod (B)
   \
    ------ InterventionParticipation ------ Intervention
                          \
                           -------- InterventionWorkingPeriod (A)
```

Right now its the time a worker spent on interventions is calculated by :
1- Taking the list of interventions for the Worker through the `Worker --(:interventions, through: :doers) -> Intervention` relation.
2- Summing the `working_duration`s for those interventions.

Now it should be 
1- Taking the list of interventions for the Worker through the `Worker --(:interventions, through: :doers) -> Intervention` relation.
2- Taking the list of interventions for the Worker through the `Worker --(:participations)--> InterventionParticipation --(:intervention)--> Intervention` relation.
3- Taking the InterventionParticipations' InterventionWorkingPeriods when they are available (`Worker --(:participations)--> InterventionParticipation --(:working_periods)--> InterventionWorkingPeriod`)
4- Summing the duration of the InterventionParticipations' WorkingPeriods (WorkingPeriod A on model).
5- Adding the sum of the `working_duration`s of the Interventions who only had the connection to Worker through InterventionDoer and not through InterventionParticipation.
