### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by nordfalk** [ekylibre/ekylibre#2507]
Hi, I am trying to register a new (test) farm.
(https://dtu-diplom-test.ekylibre.farm)

After registration I get to
https://dtu-diplom-test.ekylibre.farm/first-run/configurations
and it stays there forever, switching randomly between 0%, 53% and 80% done endlessly.

![image](https://user-images.githubusercontent.com/1143272/56018019-3cec9980-5d01-11e9-890e-fb3d0f12aa15.png)

![image](https://user-images.githubusercontent.com/1143272/56018046-4bd34c00-5d01-11e9-85a4-9299f8c46714.png)

![image](https://user-images.githubusercontent.com/1143272/56018139-8f2dba80-5d01-11e9-8af9-753087135bb7.png)

It has done so for an hour now.
Logging in from a different browser just redirects me to https://dtu-diplom-test.ekylibre.farm/first-run/configurations .

**Comment by nordfalk** [comment]
It works now:

> 
> Support (Ekylibre)   12 avr. 10:31 CEST   Hello,  Your farm has been unlocked. You can access it now.  Pierre, équipe support Ekylibre |   | Support (Ekylibre)   12 avr. 10:31 CEST   Hello,  Your farm has been unlocked. You can access it now.  Pierre, équipe support Ekylibre
> -- | -- | --
>   | Support (Ekylibre)   12 avr. 10:31 CEST   Hello,  Your farm has been unlocked. You can access it now.  Pierre, équipe support Ekylibre
> 

However I still thinks it's a bug that it is switching randomly between 0%, 53% and 80% done endlessly, so keeping this open.

**Comment by Aquaj** [comment]
Hi @nordfalk,

It is weird indeed that it would switch. I would've expected it to stay put at 80%, which is an issue we already noted can happen when an application setup job fails.
I was the one handling your issue this morning and I didn't see anything that would make it do that. We will watch out for similar issues but since this part of the app is not handled by the code in this repository (but by a plugin), I'm still closing this issue here (and re-opening it on the proper repository).

Some changes are expected on how we handle application setups in the coming few months, which might also resolve the issue.

Thank you for raising this to our attention, still.

**Comment by Aquaj** [comment]
Issue opened internally in ekylibre/ekylibre-hajimari#32. Closing here.
