### ISSUE TITLE
Search in the field "Storage" in parcel

### ISSUE THREAD

**Issue by AlexisLeC** [ekylibre/ekylibre#623]
While making a new parcel : 
the field "storage" fails at retrieving a configured product (e.g. a variant of "Réserve de produits phytosanitaires").

It cannot search.

**Comment by PH64** [comment]
The field "storage" search the "building division" (from stock area variant). When this "building division" exists, it appear in the list, but when we want to create a new from this list, it's create a product and not a bulding division
![capture du 2016-05-10 10-50-32](https://cloud.githubusercontent.com/assets/12525665/15140795/10ec29fc-169d-11e6-8af0-464a1b1d5a19.png)

**Comment by AlexisLeC** [comment]
Does it run for you ? As an example, if I try "Aire" (from Aire stockage fourrage et matériel) in the demo, nothing is found ?

**Comment by PH64** [comment]
It's because this buildings division are derivative from a variant with a type of product, which don't have capacity to stock "product".
For example "Aire" (from Aire stockage fourrage et matériel) are coming from variant "zone accueillant des animaux" from type of product "Zone dédiée aux animaux" which have capacity to stock only "animal". If you add capacity stocker "produit", it works.
If you create a building division with a variant "Pièce ou zone d’un bâtiment", you don't have problem.

**Comment by AlexisLeC** [comment]
ohh that seems far-fetched to me. There should be docs for that ...
