### ISSUE TITLE
Error importing equipement

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#725]
v2.0.0.rc23

I'm getting error importing equipment from a CVS file based on [equipement.csv](https://github.com/ekylibre/first_run-demo/blob/master/alamano/equipments.csv) from **alamano first-run** .

**Error:**
`Import Ekylibre equipments failed: Measure can't be converted from one dimension (none) to an other (power)`

Any ideas ? My file: [equipments.csv](https://github.com/ekylibre/ekylibre/files/304473/equipments.txt)

**Comment by Nicephore17** [comment]
I passed last error by changing **"Population : 1; Motor_power : 200 HP"** to **Population : 1**.
We probably have a problem with HP (horse power). Does Ekylibre expects CV (chevaux) ?

Now I get this error

`Import Ekylibre equipments failed: No variant exist in NOMENCLATURE for :Windrower`

Unless the variant is defined:

![windrowervariant](https://cloud.githubusercontent.com/assets/17082331/15893356/5f8bf698-2d7f-11e6-95c9-b31f348e4af8.PNG)

**Comment by Nicephore17** [comment]
Corrected while defining **windrower** as **Number** for Windrower variant.
Then... Same error with the rake !!!

Why does it work well with **tractors** but not with other type of equipment ?

**Comment by Nicephore17** [comment]
Now It working. After updating CSV file as follow and adding also **hay_rake** as **Number** for Hay rake variant.......

[equipments.csv](https://github.com/ekylibre/ekylibre/files/304686/equipments.txt)

**Comment by EmmaDorie** [comment]
Hi,
For indicator **motor_power**, unit **ch** is expected.

For variant, the exchanger expected a **product_nature_variant** which exist in **nomenclature** (like tractor) or the number of a **Product variant** registered in your **data base** (like windrower).

In Ekylibre nomenclature, windrower is registered with the name "mower", that's why you had the message :
`Import Ekylibre equipments failed: No variant exist in NOMENCLATURE for :Windrower`
If you want to check the nomenclature : http://open-nomenclature.org/nomenclatures

**Comment by EmmaDorie** [comment]
If it's Ok for you, can we close this issue @Nicephore17 ?

**Comment by Nicephore17** [comment]
What about using hp instead of cv for power ?

**Comment by EmmaDorie** [comment]
You can't use cv. Only the symbol ch is undersand with this exchanger.

**Comment by Nicephore17** [comment]
I meant "using **hp** instead of **ch**". Sorry.
