### ISSUE TITLE
Invalid tool in soil loosening intervention

### ISSUE THREAD

**Issue by Nicephore17** [ekylibre/ekylibre#764]
v2.0.0rc24

Intervention shows 2 tools (subsoiler) with different variant/family:

![intsubsoiler01](https://cloud.githubusercontent.com/assets/17082331/16195564/836ba610-36fa-11e6-9117-7c8ec478f401.PNG)

When editing only one is actually set (which is the normal behavior):
![intsubsoiler02](https://cloud.githubusercontent.com/assets/17082331/16195583/98ca01be-36fa-11e6-8afe-b2f8a371f54e.PNG)

**Comment by PH64** [comment]
@burisu, @EmmaDorie, 
I think I know which way the problem:
- The name of the tool is passed from harrow to soil loosener
- If we modify the operation, the tool no longer appears and if we add a soil loosener, in summary we see 2 tools

The problem is the same for stubbling that was create with cultipacker

**Comment by Nicephore17** [comment]
You sound right: I had to change tractors references on my subsoiling operation for some reasons... Any idea on how I could correct this without deleting them ?

**Comment by Nicephore17** [comment]
Any way to correct other than delete and create again my interventions ?
